---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
resources:
  - namespace.yaml
  - source.yaml
  - helmrelease.yaml
secretGenerator:
  - name: sealed-secrets-values-base
    namespace: sealed-secrets
    type: Opaque
    files:
      - values.yaml=helm-values/values-2.17.3.yaml
    options:
      disableNameSuffixHash: true
