---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: opencenter-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/rackerlabs/openCenter-gitops-base.git
  ref:
    branch: main
