apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  interval: 30s
  driftDetection:
    mode: enabled
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values
      valuesKey: hardened_values_4.13.0.yaml
    - kind: ConfigMap
      name: ingress-nginx-values
      valuesKey: override_values.yaml
