---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  releaseName: loki-distributed
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: loki-distributed
  chart:
    spec:
      chart: loki-distributed
      version: 0.80.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki-distributed
  valuesFrom:
    - kind: Secret
      name: loki-distributed-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: loki-distributed-values-override
      valuesKey: override.yaml
      optional: true
