---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opencenter-cloud
spec:
  url: oci://ghcr.io/opencenter-cloud
  interval: 1h
  type: oci
  secretRef:
    name: oci-creds
