---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: observability
spec:
  releaseName: mimir-distributed
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: mimir-distributed
  chart:
    spec:
      chart: mimir-distributed
      version: 5.8.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: mimir-distributed
  valuesFrom:
    - kind: Secret
      name: mimir-distributed-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: mimir-distributed-values-override
      valuesKey: override.yaml
      optional: true
