---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  releaseName: postgres-operator
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: postgres-operator
  chart:
    spec:
      chart: postgres-operator
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
        namespace: postgres-operator
  valuesFrom:
    - kind: Secret
      name: postgres-operator-values-base
      valuesKey: values.yaml
    - kind: Secret
      name: postgres-operator-values-enterprise
      valuesKey: hardened-enterprise.yaml
      optional: true
    - kind: Secret
      name: postgres-operator-values-override
      valuesKey: override.yaml
      optional: true
