# oidc-cluster-admins - Full cluster-admin access for OIDC cluster admins
# oidc-read-only - Cluster-wide read-only access
# oidc-namespace-admins - Admin rights in namespaces labeled `rbac.opencenter.io/admin="true"`
# oidc-security-team - Security team: view cluster + admin in namespaces labeled `security.opencenter.io/managed="true"`
# oidc-observability - Observability group: view + extras for metrics/logs/monitoring
# oidc-platform-team - Platform team: manage only rbac-manager CRDs
# oidc-k8s-ops – bind ops group to k8s-ops
# k8s-ops - broad read-only (no Secrets, no write) for ops team
# observability-extras - Adds metrics/logs/nodes access to 'view' for observability
# rbacmanager-crd-admin - Manages rbac-manager RBACDefinition CRDs

# ClusterRole: k8s-ops – broad read-only (no Secrets, no write)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-ops
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - configmaps
      - serviceaccounts
      - resourcequotas
      - limitranges
      - persistentvolumeclaims
      - replicationcontrollers
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies", "ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      ["storageclasses", "csidrivers", "csinodes", "csistoragecapacities"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/healthz", "/readyz", "/livez", "/version"]
    verbs: ["get"]
---
# 'observability-extras' ClusterRole – adds metrics/logs/nodes access to 'view'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-extras
rules:
  - apiGroups: [""]
    resources:
      [nodes, nodes/proxy, nodes/metrics, nodes/stats, services/proxy, pods/log]
    verbs: [get, list, watch]
  - nonResourceURLs: ["/metrics", "/healthz", "/readyz", "/livez", "/version"]
    verbs: [get]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      [
        prometheuses,
        servicemonitors,
        podmonitors,
        alertmanagers,
        thanosrulers,
        prometheusrules,
        alertmanagerconfigs,
      ]
    verbs: [get, list, watch]

---
# Let "platform team" manage only rbac-manager CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbacmanager-crd-admin
rules:
  - apiGroups: ["rbacmanager.reactiveops.io"]
    resources: ["rbacdefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# Cluster admins
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-cluster-admins
  namespace: rbac-system
rbacBindings:
  - name: cluster-admins
    subjects:
      - kind: Group
        name: "oidc:cluster-admins"
    clusterRoleBindings:
      - clusterRole: cluster-admin

---
# Cluster viewers
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-read-only
  namespace: rbac-system
rbacBindings:
  - name: cluster-view
    subjects:
      - kind: Group
        name: "oidc:read-only"
    clusterRoleBindings:
      - clusterRole: view

---
# Observability — 'view' plus extras, cluster-scoped
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-observability
  namespace: rbac-system
rbacBindings:
  - name: observability-view
    subjects:
      - kind: Group
        name: "oidc:observability"
    clusterRoleBindings:
      - clusterRole: view
  - name: observability-extras
    subjects:
      - kind: Group
        name: "oidc:observability"
    clusterRoleBindings:
      - clusterRole: observability-extras

---
# Namespace admins
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-namespace-admins
  namespace: rbac-system
rbacBindings:
  - name: ns-admins
    subjects:
      - kind: Group
        name: "oidc:namespace-admins"
    roleBindings:
      - clusterRole: admin
        namespaceSelector:
          matchLabels:
            rbac.opencenter.io/admin: "true"

---
# Security team — cluster read + admin in security namespaces
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-security-team
  namespace: rbac-system
rbacBindings:
  - name: security-read
    subjects:
      - kind: Group
        name: "oidc:security-team"
    clusterRoleBindings:
      - clusterRole: view
  - name: security-ns-admin
    subjects:
      - kind: Group
        name: "oidc:security-team"
    roleBindings:
      - clusterRole: admin
        namespaceSelector:
          matchLabels:
            security.opencenter.io/managed: "true"

---
# Platform team — manage only rbac-manager CRDs
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-platform-team
  namespace: rbac-system
rbacBindings:
  - name: platform-rbacdefs-admin
    subjects:
      - kind: Group
        name: "oidc:platform-team"
    clusterRoleBindings:
      - clusterRole: rbacmanager-crd-admin
---
# oidc-k8s-ops – bind ops group to k8s-ops
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-k8s-ops
  namespace: rbac-system
rbacBindings:
  - name: k8s-ops
    subjects:
      - kind: Group
        name: "oidc:k8s-ops"
        apiGroup: rbac.authorization.k8s.io
    clusterRoleBindings:
      - clusterRole: k8s-ops
