---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-kube-stack
  namespace: observability
spec:
  releaseName: opentelemetry-kube-stack
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: observability
  chart:
    spec:
      chart: opentelemetry-kube-stack
      version: 0.11.1
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: observability
  valuesFrom:
    - kind: Secret
      name: opentelemetry-kube-stack-values-base
      valuesKey: values.yaml
    - kind: Secret
      name: opentelemetry-kube-stack-values-enterprise
      valuesKey: hardened-enterprise.yaml
      optional: true
    - kind: Secret
      name: opentelemetry-kube-stack-values-override
      valuesKey: override.yaml
      optional: true
