---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - source.yaml
  - longhorn-general-storageclass.yaml
  - longhorn-general-multi-attach-storageclass.yaml
  - helmrelease.yaml

secretGenerator:
  - name: longhorn-values-base
    namespace: longhorn-system
    type: Opaque
    files:
      - values.yaml=helm-values/values-v1.10.0.yaml
    options:
      disableNameSuffixHash: true
