---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/0/failurePolicy
        target:
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: istio-system
  chart:
    spec:
      chart: base
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  valuesFrom:
    - kind: Secret
      name: istio-base-values-base
      valuesKey: values.yaml
    - kind: Secret
      name: istio-base-values-enterprise
      valuesKey: hardened-enterprise.yaml
      optional: true
    - kind: Secret
      name: istio-base-values-override
      valuesKey: override.yaml
      optional: true
