---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  valuesFrom:
    - kind: Secret
      name: istio-values-base
      valuesKey: values.yaml
    - kind: Secret
      name: istio-values-enterprise
      valuesKey: hardened-enterprise.yaml
      optional: true
    - kind: Secret
      name: istio-values-override
      valuesKey: override.yaml
      optional: true
