# RBAC Definitions for OIDC Integration
# These are example RBACDefinition custom resources that users can apply
# to automatically manage RBAC based on OIDC group membership
#
# Group Structure:
# - oidc:admins: Full cluster admin access
# - oidc:developers: Read-only cluster access
# - oidc:monitoring-users: Dashboard read-only access
# - oidc:observability-team: Comprehensive monitoring (cluster-wide)
# - oidc:platform-team: Infrastructure management
# - oidc:security-team: Audit and security namespace access
# - oidc:viewer: Read-only access to the default namespace
# - oidc:namespace-admins: Namespace creation and management
# - oidc:development-developers: Development namespace access
# - oidc:staging-developers: Staging namespace access
# - oidc:production-developers: Production namespace access
#
# Namespace Labels Required:
# - observability.openCenter.io/managed=true (for monitoring namespaces)
# - security.openCenter.io/managed=true (for security namespaces)
# - environment={development|staging|production} (for env-specific access)

---
# Developer access - read-only cluster access
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-developers
  namespace: rbac-system
spec:
  rbacBindings:
    - name: developers-view-access
      subjects:
        - kind: Group
          name: "oidc:developers"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io

---
# Admin access - full cluster admin
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-admins
  namespace: rbac-system
spec:
  rbacBindings:
    - name: admins-cluster-admin
      subjects:
        - kind: Group
          name: "oidc:admins"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io

---
# Namespace admins - namespace creation and management
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-namespace-admins
  namespace: rbac-system
spec:
  rbacBindings:
    - name: namespace-creation-access
      subjects:
        - kind: Group
          name: "oidc:namespace-admins"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: system:namespace-admin
        apiGroup: rbac.authorization.k8s.io

---
# Namespace developers - edit access to specific namespaces
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-namespace-developers
  namespace: rbac-system
spec:
  rbacBindings:
    # Development namespace access
    - name: dev-namespace-edit
      subjects:
        - kind: Group
          name: "oidc:development-developers"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io
      namespaceSelector:
        matchLabels:
          environment: development

    # Staging namespace access
    - name: staging-namespace-edit
      subjects:
        - kind: Group
          name: "oidc:staging-developers"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io
      namespaceSelector:
        matchLabels:
          environment: staging

    # Production namespace access
    - name: production-namespace-edit
      subjects:
        - kind: Group
          name: "oidc:production-developers"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io
      namespaceSelector:
        matchLabels:
          environment: production

---
# Platform team - cluster management access
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-platform-team
  namespace: rbac-system
spec:
  rbacBindings:
    - name: platform-infrastructure-access
      subjects:
        - kind: Group
          name: "oidc:platform-team"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io

    # Allow platform team to manage RBAC
    - name: platform-rbac-management
      subjects:
        - kind: Group
          name: "oidc:platform-team"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: rbac-manager
        apiGroup: rbac.authorization.k8s.io

---
# Security team - audit and monitoring access
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-security-team
  namespace: rbac-system
spec:
  rbacBindings:
    - name: security-audit-access
      subjects:
        - kind: Group
          name: "oidc:security-team"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io

    # Access to security namespaces
    - name: security-namespace-admin
      subjects:
        - kind: Group
          name: "oidc:security-team"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: admin
        apiGroup: rbac.authorization.k8s.io
      namespaceSelector:
        matchLabels:
          security.openCenter.io/managed: "true"

---
# Observability team - comprehensive monitoring access
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-observability-team
  namespace: rbac-system
spec:
  rbacBindings:
    # Cluster-wide read access for monitoring all resources
    - name: observability-cluster-reader
      subjects:
        - kind: Group
          name: "oidc:observability-team"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: cluster-reader
        apiGroup: rbac.authorization.k8s.io

    # Access to monitoring CRDs and resources
    - name: observability-monitoring-resources
      subjects:
        - kind: Group
          name: "oidc:observability-team"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: system:monitoring
        apiGroup: rbac.authorization.k8s.io

    # Admin access to observability namespaces for managing monitoring tools
    - name: observability-namespace-admin
      subjects:
        - kind: Group
          name: "oidc:observability-team"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: admin
        apiGroup: rbac.authorization.k8s.io
      namespaceSelector:
        matchLabels:
          observability.openCenter.io/managed: "true"

---
# Viewer access - read-only access to default namespace
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-viewer
  namespace: rbac-system
spec:
  rbacBindings:
    - name: viewer-default-namespace
      subjects:
        - kind: Group
          name: "oidc:viewer"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io
      namespaceSelector:
        matchLabels:
          name: default

---
# Read-only monitoring access for developers and other teams
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: oidc-monitoring-readonly
  namespace: rbac-system
spec:
  rbacBindings:
    # Read-only access to monitoring dashboards and metrics
    - name: monitoring-dashboard-access
      subjects:
        - kind: Group
          name: "oidc:monitoring-users"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io

    # Access to view monitoring resources (Grafana dashboards, etc.)
    - name: monitoring-resources-view
      subjects:
        - kind: Group
          name: "oidc:monitoring-users"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io
      namespaceSelector:
        matchLabels:
          observability.openCenter.io/managed: "true"
