---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: false
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
  valuesFrom:
    - kind: Secret
      name: harbor-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: harbor-values-override
      valuesKey: override.yaml
      optional: true
