apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  interval: 30s
  driftDetection:
    mode: enabled
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      version: 25.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: keycloak-values
      valuesKey: hardened.yaml
    - kind: Secret
      name: keycloak-values
      valuesKey: override.yaml 
