---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description:
      This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  interval: 1h0m0s
  valuesFrom:
    - kind: Secret
      name: weave-gitops-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: weave-gitops-values-override
      valuesKey: override.yaml
      optional: true
