resource "openstack_identity_project_v3" "project" {
  count       = var.openstack_project_id == "" ? 1 : 0
  description = "Automatically generated by terraform-rke"
  name        = var.openstack_user_name
}

resource "openstack_identity_user_v3" "user" {
  default_project_id = var.openstack_project_id == "" ? openstack_identity_project_v3.project[0].id : var.openstack_project_id
  domain_id          = var.openstack_project_id == "" ? openstack_identity_project_v3.project[0].domain_id : var.openstack_domain_id
  enabled            = true
  extra = {
    email = var.openstack_user_email != "" ? var.openstack_user_email : format("%s@fake.com", var.openstack_user_name)
  }
  name                                  = var.openstack_user_name
  password                              = var.openstack_user_password
  ignore_change_password_upon_first_use = true
  ignore_password_expiry                = true
}

data "openstack_identity_role_v3" "member_old" {
  name = "_member_"
}

resource "openstack_identity_role_assignment_v3" "member_role_assignment_old" {
  user_id    = openstack_identity_user_v3.user.id
  project_id = var.openstack_project_id == "" ? openstack_identity_project_v3.project[0].id : var.openstack_project_id
  role_id    = data.openstack_identity_role_v3.member_old.id
}

data "openstack_identity_role_v3" "member" {
  name = "member"
}

resource "openstack_identity_role_assignment_v3" "member_role_assignment" {
  user_id    = openstack_identity_user_v3.user.id
  project_id = var.openstack_project_id == "" ? openstack_identity_project_v3.project[0].id : var.openstack_project_id
  role_id    = data.openstack_identity_role_v3.member.id
}

data "openstack_identity_role_v3" "load_balancer_member" {
  name = "load-balancer_member"
}

resource "openstack_identity_role_assignment_v3" "load_balancer_member_role_assignment" {
  user_id    = openstack_identity_user_v3.user.id
  project_id = var.openstack_project_id == "" ? openstack_identity_project_v3.project[0].id : var.openstack_project_id
  role_id    = data.openstack_identity_role_v3.load_balancer_member.id
}

resource "openstack_blockstorage_quotaset_v3" "blockstorage_quotaset" {
  project_id           = var.openstack_project_id == "" ? openstack_identity_project_v3.project[0].id : var.openstack_project_id
  volumes              = var.quotas.volumes
  snapshots            = var.quotas.snapshots
  gigabytes            = var.quotas.gigabytes
  per_volume_gigabytes = var.quotas.per_volume_gigabytes
}

resource "openstack_compute_quotaset_v2" "compute_quotaset" {
  project_id                  = var.openstack_project_id == "" ? openstack_identity_project_v3.project[0].id : var.openstack_project_id
  ram                         = var.quotas.ram
  cores                       = var.quotas.cores
  instances                   = var.quotas.instances
  key_pairs                   = var.quotas.key_pairs
  security_group_rules        = var.quotas.security_group_rules
  security_groups             = var.quotas.security_groups
  server_group_members        = var.quotas.server_group_members
  server_groups               = var.quotas.server_groups
  floating_ips                = var.quotas.floating_ips
  injected_file_content_bytes = var.quotas.injected_file_content_bytes
  injected_file_path_bytes    = var.quotas.injected_file_path_bytes
  injected_files              = var.quotas.injected_files
  metadata_items              = var.quotas.metadata_items
}

resource "openstack_compute_flavor_v2" "mk8s_small" {
  name      = var.small_flavor.name != "" ? var.small_flavor.name : format("%s-mk8s-small", var.openstack_user_name)
  ram       = var.small_flavor.ram
  vcpus     = var.small_flavor.vcpus
  disk      = var.small_flavor.disk
  is_public = true

  # This is set so that the roles are not unassigned before the VMs with these flavors are destroyed.
  depends_on = [
    openstack_identity_role_assignment_v3.member_role_assignment,
    openstack_identity_role_assignment_v3.load_balancer_member_role_assignment,
  ]
}

resource "openstack_compute_flavor_v2" "mk8s_medium" {
  name      = var.medium_flavor.name != "" ? var.medium_flavor.name : format("%s-mk8s-medium", var.openstack_user_name)
  ram       = var.medium_flavor.ram
  vcpus     = var.medium_flavor.vcpus
  disk      = var.medium_flavor.disk
  is_public = true

  # This is set so that the roles are not unassigned before the VMs with these flavors are destroyed.
  depends_on = [
    openstack_identity_role_assignment_v3.member_role_assignment,
    openstack_identity_role_assignment_v3.load_balancer_member_role_assignment,
  ]
}

resource "openstack_compute_flavor_v2" "mk8s_large" {
  name      = var.large_flavor.name != "" ? var.large_flavor.name : format("%s-mk8s-large", var.openstack_user_name)
  ram       = var.large_flavor.ram
  vcpus     = var.large_flavor.vcpus
  disk      = var.large_flavor.disk
  is_public = true

  # This is set so that the roles are not unassigned before the VMs with these flavors are destroyed.
  depends_on = [
    openstack_identity_role_assignment_v3.member_role_assignment,
    openstack_identity_role_assignment_v3.load_balancer_member_role_assignment,
  ]
}

resource "openstack_compute_flavor_v2" "mk8s_xlarge" {
  name      = var.xlarge_flavor.name != "" ? var.xlarge_flavor.name : format("%s-mk8s-xlarge", var.openstack_user_name)
  ram       = var.xlarge_flavor.ram
  vcpus     = var.xlarge_flavor.vcpus
  disk      = var.xlarge_flavor.disk
  is_public = true

  # This is set so that the roles are not unassigned before the VMs with these flavors are destroyed.
  depends_on = [
    openstack_identity_role_assignment_v3.member_role_assignment,
    openstack_identity_role_assignment_v3.load_balancer_member_role_assignment,
  ]
}

resource "openstack_networking_network_v2" "network_vlan" {
  count          = var.vlan_id == "" ? 0 : 1
  name           = "${var.openstack_user_name}-vlan-k8s"
  admin_state_up = "true"
  tenant_id      = openstack_identity_project_v3.project[0].id
  mtu            = var.vlan_mtu

  segments {
    physical_network = var.network_provider
    segmentation_id  = var.vlan_id
    network_type     = "vlan"
  }
}