---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: "v1.10.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    longhornDriver:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        longhorn.io/storage-node: "enabled"
    longhornRecoveryBackend:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        longhorn.io/storage-node: "enabled"
    longhornUI:
      nodeSelector:
        longhorn.io/control-storage-node: "enabled"
    longhornConversionWebhook:
      nodeSelector:
        longhorn.io/control-storage-node: "enabled"
    longhornAdmissionWebhook:
      nodeSelector:
        longhorn.io/control-storage-node: "enabled"
