---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  releaseName: istio-ingress
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: istio-ingress
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.28.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  valuesFrom:
    - kind: Secret
      name: istio-gateway-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: istio-gateway-values-override
      valuesKey: override.yaml
      optional: true
