---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  interval: 5m
  timeout: 5m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: velero
  chart:
    spec:
      chart: velero
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  valuesFrom:
    - kind: Secret
      name: velero-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: velero-values-override
      valuesKey: override.yaml
      optional: true
