---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - namespace.yaml
  - source.yaml
  - helmrelease.yaml
secretGenerator:
  - name: velero-values-base
    namespace: velero
    type: Opaque
    files:
      - values.yaml=helm-values/values-10.1.1.yaml
    options:
      disableNameSuffixHash: true
