---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  releaseName: falco
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: falco
  chart:
    spec:
      chart: falco
      version: 6.2.5
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: falco
  valuesFrom:
    - kind: Secret
      name: falco-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: falco-values-override
      valuesKey: override.yaml
      optional: true
