---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
      namespace: flux-system
    - name: envoy-gateway-api
      namespace: flux-system
  interval: 1m
  path: ./applications/overlays/delta/managed-services/gateway/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
