---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-shared
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-sources
      namespace: flux-system
  interval: 1m
  path: ./applications/base/managed-services/keycloak/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  dependsOn:
    - name: keycloak-shared
      namespace: flux-system
  interval: 1m
  path: ./applications/overlays/delta/managed-services/keycloak
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  targetNamespace: keycloak
  wait: true
