---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-shared
  namespace: flux-system
spec:
  interval: 1m
  path: ./applications/base/managed-services/sealed-secrets/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets-shared
      namespace: flux-system
  interval: 1m
  path: ./applications/overlays/delta/managed-services/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: sealed-secrets
  wait: true
