---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: observability
spec:
  releaseName: opentelemetry-operator
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: observability
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.98.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: observability
  valuesFrom:
    - kind: Secret
      name: opentelemetry-operator-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: opentelemetry-operator-values-override
      valuesKey: override.yaml
      optional: true