---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  path: "./applications/overlays/delta/managed-services/sources/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: opencenter
      app.kubernetes.io/managed-by: flux
      opencenter/managed-by: opencenter
