---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.28.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  valuesFrom:
    - kind: Secret
      name: istiod-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: istiod-values-override
      valuesKey: override.yaml
      optional: true
