apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-subscription
  namespace: keycloak
spec:
  name: keycloak-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  channel: fast
  installPlanApproval: Manual
