---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  releaseName: headlamp
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: kube-system
  chart:
    spec:
      chart: headlamp
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: kube-system
  valuesFrom:
    - kind: Secret
      name: headlamp-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: headlamp-values-override
      valuesKey: override.yaml
      optional: true
