# OIDC Secret Template for Headlamp
# This is a template for creating the OIDC configuration secret
# Replace placeholders with your actual OIDC provider details

apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc-config
  namespace: kube-system
type: Opaque
stringData:
  # OIDC Client Configuration
  clientID: "YOUR_OIDC_CLIENT_ID"
  clientSecret: "YOUR_OIDC_CLIENT_SECRET"

  # OIDC Provider Configuration
  issuerURL: "https://your-oidc-provider.com/realms/your-realm"

  # OAuth Scopes (space-separated)
  scopes: "openid profile email groups"

  # Callback URL - must match your ingress configuration
  callbackURL: "https://headlamp.example.com/oidc-callback"

  # Optional: Token validation settings
  # validatorClientID: "YOUR_VALIDATOR_CLIENT_ID"
  # validatorIssuerURL: "https://your-oidc-provider.com/realms/your-realm"

---
# Alternative: Using SealedSecret for GitOps workflow
# Uncomment and configure if using sealed-secrets operator
#
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: headlamp-oidc-config
#   namespace: kube-system
# spec:
#   encryptedData:
#     clientID: AgA...  # Encrypted with kubeseal
#     clientSecret: AgA...  # Encrypted with kubeseal
#     issuerURL: AgA...  # Encrypted with kubeseal
#     scopes: AgA...  # Encrypted with kubeseal
#     callbackURL: AgA...  # Encrypted with kubeseal
#   template:
#     metadata:
#       name: headlamp-oidc-config
#       namespace: kube-system
#     type: Opaque