---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openstack-base
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  interval: 1m
  path: ./applications/base/genestack/base-kustomize/openstack/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: genestack-root
    namespace: flux-system
  wait: true
