apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-envoy-gateway
  namespace: envoy-gateway-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
