apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  releaseName: sealed-secrets
  interval: 30s
  driftDetection:
    mode: enabled
  targetNamespace: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.3
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: sealed-secrets-values
      valuesKey: hardened_values_2.17.3.yaml
    - kind: ConfigMap
      name: sealed-secrets-values
      valuesKey: override_values.yaml
