---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  releaseName: gatekeeper
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: gatekeeper-system
  chart:
    spec:
      chart: gatekeeper
      version: 3.20.1
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: gatekeeper-system
  valuesFrom:
    - kind: Secret
      name: gatekeeper-values-base
      valuesKey: hardened.yaml
    - kind: Secret
      name: gatekeeper-values-override
      valuesKey: override.yaml
      optional: true
