---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
  namespace: keycloak
  labels:
    app: keycloak
    component: metrics
spec:
  selector:
    matchLabels:
      app: keycloak
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 25s
      scheme: http
      honorLabels: true
      metricRelabelings:
        # Add namespace label to metrics
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        # Add pod name label
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        # Add service name label
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
  namespaceSelector:
    matchNames:
      - keycloak