---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources: [./namespace.yaml, ./source.yaml, ./helmrelease.yaml]
secretGenerator:
  - name: ingress-nginx-values-base
    type: Opaque
    files: [hardened.yaml=helm-values/hardened-values-4.12.6.yaml]
    options:
      disableNameSuffixHash: true
