---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - "./ipaddresspool.yaml"
  - "./l2advertisement.yaml"
secretGenerator:
  - name: metallb-values-override
    type: Opaque
    files: [override.yaml=helm-values/override-values.yaml]
    options:
      disableNameSuffixHash: true
